### ISSUE TITLE
TypeError: mkdir() got an unexpected keyword argument 'exist_ok'

### ISSUE THREAD

**Issue by daviderickson** [gethvi/iDRAC6VirtualConsoleLauncher#4]
Seeing the below on the latest version of code

Traceback (most recent call last):
  File "iDRAC6VirtualConsoleLauncher.py", line 92, in <module>
    main()
  File "iDRAC6VirtualConsoleLauncher.py", line 46, in main
    libdir.mkdir(parents=True, exist_ok=True)
TypeError: mkdir() got an unexpected keyword argument 'exist_ok'

**Comment by daviderickson** [comment]
I had a few other failures as well even after modifying the above.. this was on Python 3.4.  Is there a minimum newer version of Python required that would be worth mentioning in the readme?

**Comment by gethvi** [comment]
Hi, thanks for this issue. I will look into it.

I developed the tool with python 3.7 where it works. My assumption is that it should work with python 3.5 and above, but I have to test it first. Then I will include this in the readme.

I do not plan to support python 3.4 as it has reached the end of life anyway.
